### ISSUE TITLE
Logos 

### ISSUE THREAD

**Issue by AndyP444** [wmcadigital/wmn-disruption-email-templates#15]
Top logo only shows the Hexagons and a long purple bar on iphone in outlook app - in outlook on PC it shows the WMN text next to it? 
At bottom it has the WMCA logo - shouldn't this be Tf
![email logo screenshot](https://user-images.githubusercontent.com/73545091/97325620-181c3080-186b-11eb-8fa2-1f34194c22e1.jpg)
WM if needed at all? 
![email logo screenshot](https://user-images.githubusercontent.com/73545091/97325770-3c780d00-186b-11eb-85be-0927319817e5.jpg)

**Comment by KaterinaKir** [comment]
WMN logo follows the mobile behaviour of the website, on a large screen we show a full logo and on a small screen we show hexagon only. In relation to TfWM logo, the brand guidelines advise to never use TfWM and WM Network together. We will remove WMCA logo at the bottom.
