### ISSUE TITLE
Bus numbers on text message

### ISSUE THREAD

**Issue by DavidS-RTCC** [wmcadigital/wmn-disruption-email-templates#17]
![image](https://user-images.githubusercontent.com/73537253/97631064-5743b080-1a28-11eb-803b-74ff4e036fb9.png)

When disruption affects multiple bus services / numbers, the presentation (on text) of bus numbers isn't that clear. With the random underlining of some part of the message. Hopefully, you can see the text image above.

**Comment by Rippled** [comment]
The stops are now seperated by a comma.
