### ISSUE TITLE
Email alert for Metro

### ISSUE THREAD

**Issue by DavidS-RTCC** [wmcadigital/wmn-disruption-email-templates#22]
This email alert was in my email box from in the week (I've been on rest days) - Hope you can see picture

I know that MM1 is the Metro, but would anyone else? - as at the top its says 'There is minor bus disruption' which is automatically created text

![image](https://user-images.githubusercontent.com/73537253/98380404-72be4500-2040-11eb-9efd-893c43238ab6.png)

**Comment by daylesalmon** [comment]
@houbly could you pick this up (the bus mode part is fine as that is an API issue that is being fixed).

Can you update the orange block so if it equals mm1 then it shows the text "MML - Birmingham - Wolverhampton - Birmingham" instead.

Thanks.
