### ISSUE TITLE
Capital letters in text message alerts

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-disruption-email-templates#27]
## Pain points
- [x] Severity is always capitalised
- [x] Messages from ICS - subject starts with a capital letter
- [x] Letters in routes from ICS are always lowercase. Should be capitalised like X8; 8A; MM1

## Examples
```There is a Minor disruption due to Incident at Long lane, Halesowen. Affects bus service(s) - x8, 14. Read more: https://disruptions.wmnetwork.co.uk/?selectedByMap=true&selectedItem=9579_TfWM```

```There is a Minor disruption Because of a fault with the signalling system between Longbridge and Redditch all lines towards Redditch are blocked.. Affects Cross City. Read more: https://disruptions.wmnetwork.co.uk/?selectedByMap=true&selectedItem=365512247```

```There is a Minor disruption due to Collision at Wolverhampton St George's/Priestfield. Read more: https://disruptions.wmnetwork.co.uk/?selectedByMap=true&selectedItem=9300_TfWM```

**Comment by Rippled** [comment]
fixed in next release

**Comment by Rippled** [comment]
this has been released
