### ISSUE TITLE
Punctuation at the end of train text message subject

### ISSUE THREAD

**Issue by mrmjprice** [wmcadigital/wmn-disruption-email-templates#28]
## Pain points
- [x] Random punctuation at the end of the ((subject)) part. Usually a colon or full stop.

## Examples
```There is a Minor disruption Because of a fault with the signalling system between Coseley and Tipton:. Affects Coventry via Birmingham International, Shrewsbury via Telford, Walsall, Wolverhampton. Read more: https://disruptions.wmnetwork.co.uk/?selectedByMap=true&selectedItem=279437634```

```There is a Major disruption Because of a points failure between Sutton Coldfield and Lichfield Trent Valley Hl:. Affects Cross City. Read more: https://disruptions.wmnetwork.co.uk/?selectedByMap=true&selectedItem=1056583800```

```There is a Minor disruption Because of a fault with the signalling system between Longbridge and Redditch all lines towards Redditch are blocked.. Affects Cross City. Read more: https://disruptions.wmnetwork.co.uk/?selectedByMap=true&selectedItem=365512247```

**Comment by Rippled** [comment]
this is live and fixed
